### ISSUE TITLE
Fix jss peer dependency

### ISSUE THREAD

**Issue by jupl** [jsstyles/jss-props-sort#1]
This plugin wants jss@^1.0.0 while other plugins want jss@^2.1.0

**Comment by kof** [comment]
right, thanks, wanna send a pr?

**Comment by jupl** [comment]
I can. I just wanted to make sure if there were any expected breaking changes that needed to be done as it's 1->2.

**Comment by kof** [comment]
nope, its just bad copy-paste)

**Comment by kof** [comment]
consider it needs to be done in x-package.json5 and then make build + increment patch version

**Comment by kof** [comment]
published
